CC=g++
CFLAGS=-std=c++0x
LDFLAGS=
EXEC=main2048Plugin main2048 mainSokobanManual mainSokobanFile mainTakinINT mainTakinCHAR

all: $(EXEC)

main2048Plugin: object/Case2048.o object/Case2048Negative.o  object/Case2048Destroy.o object/Plateau2048.o object/Plateau2048Plugin.o object/CaseGeneric.o object/main2048Plugin.o
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	rm -rf object/*.o

mrproper: clean
	rm -rf $(EXEC)